import { StyleSheet, Platform, StatusBar, Dimensions } from 'react-native';
import { GOLD, GOLD_LIGHT, BG_DARK, BG_CARD, BG_SURFACE, TEXT_PRIMARY, TEXT_MUTED } from './constants';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const STATUSBAR_HEIGHT = Platform.OS === 'android' ? (StatusBar.currentHeight || 24) : 0;

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: BG_DARK,
    paddingTop: STATUSBAR_HEIGHT,
  },

  screenTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  exitBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#444',
    backgroundColor: '#1A1A1A',
  },
  exitBtnText: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    fontFamily: 'Georgia',
  },

  // ── ACTION FEED ──
  feedContainer: {
    marginHorizontal: 16,
    marginBottom: 4,
    backgroundColor: BG_SURFACE,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
    padding: 14,
  },
  feedTitle: {
    color: TEXT_MUTED,
    fontSize: 9,
    letterSpacing: 3,
    fontFamily: 'Georgia',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  feedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 7,
    gap: 10,
  },
  feedDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },
  feedText: {
    color: TEXT_PRIMARY,
    fontSize: 13,
    fontFamily: 'Georgia',
    flex: 1,
  },
  feedTextKnock: {
    color: '#FF8C00',
    fontWeight: '700',
  },

  // ── MODAL ──
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
  },
  modalBox: {
    backgroundColor: BG_SURFACE,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: GOLD,
    padding: 28,
    width: '100%',
    alignItems: 'center',
    shadowColor: GOLD,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
  },
  modalTitle: {
    color: GOLD,
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 4,
    fontFamily: 'Georgia',
    marginBottom: 12,
  },
  modalBody: {
    color: TEXT_MUTED,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
    fontFamily: 'Georgia',
    marginBottom: 28,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  modalCancelBtn: {
    flex: 1,
    backgroundColor: BG_CARD,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#444',
  },
  modalCancelText: {
    color: TEXT_PRIMARY,
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 2,
    fontFamily: 'Georgia',
  },
  modalConfirmBtn: {
    flex: 1,
    backgroundColor: '#3A0000',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EF4444',
  },
  modalConfirmText: {
    color: '#EF4444',
    fontWeight: '800',
    fontSize: 14,
    letterSpacing: 2,
    fontFamily: 'Georgia',
  },

  // ── CARD ──
  cardBase: {
    backgroundColor: '#FAFAF7',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DDD',
    padding: 4,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  cardFaceDown: {
    backgroundColor: '#1A1A2E',
    borderColor: GOLD,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardBackPattern: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: GOLD,
    borderRadius: 4,
    margin: 2,
  },
  cardSelected: {
    borderColor: GOLD,
    borderWidth: 3,
    transform: [{ translateY: -10 }],
    shadowColor: GOLD,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 8,
    elevation: 12,
  },
  cardCornerText: {
    position: 'absolute',
    top: 3,
    left: 4,
    fontWeight: '800',
    fontFamily: 'Georgia',
  },
  cardCornerSuit: {
    position: 'absolute',
    bottom: 3,
    right: 4,
    fontWeight: '800',
    fontFamily: 'Georgia',
  },
  cardCenter: {
    fontWeight: '400',
    fontFamily: 'Georgia',
  },

  // ── HEARTS ──
  heartsRow: { flexDirection: 'row', gap: 2, marginTop: 4 },
  heart: { fontSize: 16 },
  heartFull: { color: '#EF4444' },
  heartEmpty: { color: '#444' },

  // ── SHARED ──
  goldButton: {
    backgroundColor: GOLD,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 48,
    alignItems: 'center',
    shadowColor: GOLD,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 8,
  },
  goldButtonText: {
    color: '#0F0F0F',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 2,
    fontFamily: 'Georgia',
  },
  screenTitle: {
    color: GOLD,
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 4,
    textAlign: 'center',
    fontFamily: 'Georgia',
  },
  divider: {
    height: 1,
    backgroundColor: '#333',
    marginVertical: 20,
  },

  // ── HOME ──
  homeContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  homeLogoArea: { alignItems: 'center', marginBottom: 24 },
  aceSpadesCard: {
    width: 90,
    height: 120,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: GOLD,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    shadowColor: GOLD,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 16,
    elevation: 10,
  },
  aceSpadesSuit: { fontSize: 40, color: '#F5F0E8', fontFamily: 'Georgia' },
  aceSpadesNum: { fontSize: 22, color: GOLD, fontWeight: '800', fontFamily: 'Georgia', letterSpacing: 2 },
  homeTitle: { fontSize: 52, fontWeight: '800', color: TEXT_PRIMARY, letterSpacing: 12, fontFamily: 'Georgia' },
  homeSubtitle: { fontSize: 14, color: GOLD, letterSpacing: 6, fontFamily: 'Georgia', marginTop: 4 },
  homeDecorLine: { width: 120, height: 2, backgroundColor: GOLD, marginVertical: 20, opacity: 0.7 },
  homeTagline: { color: TEXT_MUTED, fontSize: 13, letterSpacing: 2, marginBottom: 40, fontFamily: 'Georgia', fontStyle: 'italic' },
  homeRulesBox: {
    marginTop: 40,
    padding: 20,
    backgroundColor: BG_SURFACE,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
    width: '100%',
  },
  homeRulesTitle: { color: GOLD, fontSize: 11, letterSpacing: 3, fontWeight: '700', marginBottom: 8, fontFamily: 'Georgia' },
  homeRulesText: { color: TEXT_MUTED, fontSize: 13, lineHeight: 20, fontFamily: 'Georgia' },

  // ── SETUP ──
  setupContainer: { padding: 24, paddingTop: 16 },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: BG_SURFACE,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#333',
  },
  stepperLabel: { color: TEXT_PRIMARY, fontSize: 16, fontWeight: '600', fontFamily: 'Georgia' },
  stepperControls: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  stepperBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: GOLD, alignItems: 'center', justifyContent: 'center' },
  stepperBtnText: { color: '#0F0F0F', fontSize: 20, fontWeight: '800', lineHeight: 24 },
  stepperValue: { color: GOLD, fontSize: 24, fontWeight: '800', fontFamily: 'Georgia', minWidth: 28, textAlign: 'center' },
  resetBtn: { backgroundColor: '#444', borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: '#666', alignItems: 'center' },
  resetBtnText: { color: TEXT_MUTED, fontSize: 10, fontWeight: '700', letterSpacing: 0.5, fontFamily: 'Georgia' },
  playerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, gap: 12 },
  colorBadge: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  colorBadgeText: { color: '#0F0F0F', fontWeight: '800', fontSize: 16, fontFamily: 'Georgia' },
  nameInput: {
    flex: 1,
    backgroundColor: BG_SURFACE,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#444',
    color: TEXT_PRIMARY,
    fontSize: 16,
    padding: 12,
    fontFamily: 'Georgia',
  },

  // ── GATE ──
  gateContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },
  gateDecor: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: BG_SURFACE,
    borderWidth: 2,
    borderColor: GOLD,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  gateCardSymbol: { fontSize: 36, color: GOLD, fontFamily: 'Georgia' },
  gateLabel: { color: TEXT_MUTED, fontSize: 11, letterSpacing: 4, marginBottom: 16, fontFamily: 'Georgia' },
  gateBadge: { borderWidth: 2, borderRadius: 16, paddingVertical: 12, paddingHorizontal: 32, marginBottom: 16 },
  gatePlayerName: { fontSize: 32, fontWeight: '800', fontFamily: 'Georgia', letterSpacing: 2 },
  gateInstructions: {
    color: TEXT_MUTED,
    fontSize: 14,
    textAlign: 'center',
    marginVertical: 24,
    lineHeight: 22,
    fontFamily: 'Georgia',
    fontStyle: 'italic',
  },

  // ── BOARD ──
  boardContainer: { padding: 16, paddingTop: 16, paddingBottom: 32 },
  boardTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    backgroundColor: BG_SURFACE,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  boardRightCluster: { alignItems: 'flex-end', gap: 8 },
  boardPlayerName: { fontSize: 20, fontWeight: '800', fontFamily: 'Georgia', letterSpacing: 1 },
  boardScoreBadge: {
    alignItems: 'center',
    backgroundColor: BG_CARD,
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: GOLD,
    minWidth: 64,
  },
  boardScoreLabel: { color: TEXT_MUTED, fontSize: 9, letterSpacing: 2, fontFamily: 'Georgia' },
  boardScoreValue: { color: GOLD, fontSize: 22, fontWeight: '800', fontFamily: 'Georgia' },
  knockBanner: {
    backgroundColor: '#2A1A00',
    borderWidth: 1,
    borderColor: GOLD,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    alignItems: 'center',
  },
  knockBannerText: { color: GOLD_LIGHT, fontSize: 13, fontFamily: 'Georgia', letterSpacing: 1 },
  pilesRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 32,
    marginBottom: 20,
    padding: 16,
    backgroundColor: BG_SURFACE,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  pileArea: { alignItems: 'center', gap: 8 },
  stackedCardWrapper: { width: 64, height: 90, position: 'relative' },
  pileTopCard: { position: 'absolute', top: 0, left: 0, width: 64, height: 90, alignItems: 'center', justifyContent: 'center' },
  stackShadow1: { position: 'absolute', top: -3, left: -3, width: 64, height: 90, opacity: 0.7 },
  stackShadow2: { position: 'absolute', top: -6, left: -6, width: 64, height: 90, opacity: 0.4 },
  emptyPile: { width: 64, height: 90, backgroundColor: '#1A1A1A', borderStyle: 'dashed', borderColor: '#444', alignItems: 'center', justifyContent: 'center' },
  emptyPileText: { color: '#444', fontSize: 8, letterSpacing: 1 },
  pileLabel: { color: TEXT_MUTED, fontSize: 10, letterSpacing: 2, fontFamily: 'Georgia' },
  pileTappable: { shadowColor: GOLD, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.5, shadowRadius: 8, elevation: 8 },
  pileTapHint: { color: GOLD, fontSize: 9, letterSpacing: 1, fontFamily: 'Georgia', opacity: 0.7, marginTop: -2 },
  actionsRow: { flexDirection: 'row', gap: 8, marginBottom: 24 },
  actionBtn: { flex: 1, backgroundColor: BG_SURFACE, borderRadius: 10, paddingVertical: 14, alignItems: 'center', borderWidth: 1, borderColor: GOLD },
  actionBtnText: { color: GOLD, fontWeight: '700', fontSize: 13, letterSpacing: 2, fontFamily: 'Georgia' },
  knockBtn: { backgroundColor: '#2A1400', borderColor: '#FF8C00' },
  knockBtnText: { color: '#FF8C00', fontWeight: '800', fontSize: 13, letterSpacing: 2, fontFamily: 'Georgia' },
  discardInstruction: { alignItems: 'center', marginBottom: 24, gap: 12 },
  discardInstructionText: { color: GOLD_LIGHT, fontSize: 14, fontFamily: 'Georgia', fontStyle: 'italic' },
  handSection: { backgroundColor: BG_SURFACE, borderRadius: 16, padding: 20, borderWidth: 1, borderColor: GOLD, alignItems: 'center' },
  handLabel: { color: TEXT_MUTED, fontSize: 10, letterSpacing: 3, marginBottom: 16, fontFamily: 'Georgia' },
  handRow: { flexDirection: 'row', gap: 12, justifyContent: 'center' },

  // ── SUMMARY ──
  summaryContainer: { padding: 20, paddingTop: 16, paddingBottom: 40 },
  summaryCard: { backgroundColor: BG_SURFACE, borderRadius: 12, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: '#333' },
  eliminatedCard: { opacity: 0.45 },
  summaryCardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, gap: 8 },
  colorDot: { width: 12, height: 12, borderRadius: 6 },
  summaryPlayerName: { fontSize: 18, fontWeight: '700', fontFamily: 'Georgia', flex: 1 },
  scatTag: { backgroundColor: '#1A2A00', color: GOLD, fontSize: 10, fontWeight: '800', letterSpacing: 1, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3, fontFamily: 'Georgia', borderWidth: 1, borderColor: GOLD },
  knockerTag: { backgroundColor: '#2A1400', color: '#FF8C00', fontSize: 10, fontWeight: '700', letterSpacing: 1, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3, fontFamily: 'Georgia' },
  eliminatedTag: { backgroundColor: '#2A0000', color: '#EF4444', fontSize: 10, fontWeight: '700', letterSpacing: 1, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3, fontFamily: 'Georgia' },
  summaryHandRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  summaryScoreBadge: { backgroundColor: BG_CARD, borderRadius: 8, borderWidth: 1, borderColor: GOLD, paddingHorizontal: 12, paddingVertical: 6, marginLeft: 8 },
  summaryScore: { color: GOLD, fontSize: 18, fontWeight: '800', fontFamily: 'Georgia' },
  summaryLifeRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  lostLifeText: { color: '#EF4444', fontSize: 12, fontFamily: 'Georgia', fontStyle: 'italic' },

  // ── SCAT SPLASH ──
  scatContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32, gap: 16 },
  scatFireworks: { fontSize: 64, marginBottom: 8 },
  scatTitle: { fontSize: 72, fontWeight: '800', color: GOLD, letterSpacing: 12, fontFamily: 'Georgia', textShadowColor: GOLD, textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 20 },
  scatBadge: { borderWidth: 2, borderRadius: 16, paddingVertical: 10, paddingHorizontal: 28 },
  scatWinnerName: { fontSize: 28, fontWeight: '800', fontFamily: 'Georgia', letterSpacing: 2 },
  scatSubtitle: { color: TEXT_MUTED, fontSize: 16, fontFamily: 'Georgia', fontStyle: 'italic', marginTop: -8 },
  scatHandRow: { flexDirection: 'row', gap: 12, marginVertical: 16 },
  scatNote: { color: '#EF4444', fontSize: 14, fontFamily: 'Georgia', fontStyle: 'italic', marginBottom: 8 },

  // ── GAME OVER ──
  gameOverContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },
  gameOverEmoji: { fontSize: 72, marginBottom: 16 },
  gameOverLabel: { color: TEXT_MUTED, fontSize: 12, letterSpacing: 6, marginBottom: 16, fontFamily: 'Georgia' },
  gameOverBadge: { borderWidth: 2, borderRadius: 20, paddingVertical: 16, paddingHorizontal: 40, marginBottom: 16 },
  gameOverName: { fontSize: 36, fontWeight: '800', fontFamily: 'Georgia', letterSpacing: 2 },
  gameOverSub: { color: TEXT_MUTED, fontSize: 14, fontFamily: 'Georgia', fontStyle: 'italic', marginBottom: 12 },

  // ── COLOR PICKER ──
  colorPickerOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.8)', alignItems: 'center', justifyContent: 'center' },
  colorPickerContainer: { backgroundColor: BG_SURFACE, borderRadius: 16, padding: 24, borderWidth: 1, borderColor: GOLD, alignItems: 'center', minWidth: 280 },
  colorPickerTitle: { color: TEXT_PRIMARY, fontSize: 18, fontWeight: '700', letterSpacing: 2, marginBottom: 16, fontFamily: 'Georgia' },
  colorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, justifyContent: 'center', marginBottom: 20 },
  colorOption: { width: 50, height: 50, borderRadius: 25, borderWidth: 2, borderColor: '#444' },
  colorPickerClose: { backgroundColor: GOLD, borderRadius: 10, paddingVertical: 12, paddingHorizontal: 24 },
  colorPickerCloseText: { color: BG_DARK, fontWeight: '800', fontSize: 14, letterSpacing: 1, fontFamily: 'Georgia' },
});
